name: Deploy to Ubuntu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: .
          remote_path: /home/ubuntu/webServer
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USERNAME }}
          remote_key: ${{ secrets.SERVER_PRIVATE_KEY }}

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/backend-matchmaking
            # Create .env file on the server
            rm -f .env
            
            
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
            # Install dependencies
            npm install
            # Start or restart the application
            pm2 reload all || pm2 start npm -- start
